# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'CometChatSwift' do
  pod 'CometChatPro', '3.0.914'
  pod 'CometChatCalls', '3.0.0'
 

end

target 'CometChat KitchenSinkTests' do
   pod 'CometChatPro', '3.0.914'
   pod 'CometChatCalls', '3.0.0'

end

target 'CometChat KitchenSink UITests' do
   pod 'CometChatPro', '3.0.914'
   pod 'CometChatCalls', '3.0.0'

end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end
